version: '3'

services:
  scraper:
    build: 
      context: .
    environment:
      - DISCORD_TOKEN_MCSN=OTk0MzMyMjAxNjQ0NzI4NDQ0.GjFRRX.b79JlA4hEvFDRI9AWBzwdCQ5C379_p4gGVG02c
      - REPEAT_TIME=3.0
